# Generated by Django 2.0.1 on 2018-01-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
            ],
        ),
    ]
