# Generated by Django 2.0.1 on 2018-01-31 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated On')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('latitude', 'longitude')},
        ),
    ]
